
library(ggpubr)
library(scatterplot3d)
#get legends for merged plot
legend_te1 <- get_legend(PsenAn_162_time1)
legend_te2 <- get_legend(PsenAn_162_PestEff2)
legend_BA <- get_legend(PsenAn_162_repair2)

legend_te22 <- get_legend(PsenAn_162_LEGEND)

legend_te1 <- as_ggplot(legend_te1)
legend_te2 <- as_ggplot(legend_te2)
legend_BA <- as_ggplot(legend_BA)

legend_te22 <- as_ggplot(legend_te22)

dev.off()
legend_3D <- (legend_te1 + legend_te22 + legend_BA +
    plot_layout(ncol = 3, nrow = 1) + 
    plot_layout(widths=unit(c(8.5,12,1.5),"cm"), height = unit(c(1),"cm")))
legend_3D
legend_te1
dev.off()
##Plot for higher pesticide costs and acquisition costs 
layout(matrix(c(1,2,3,4), nrow = 2, ncol = 2, byrow = TRUE))
PsenAn_162_teValuePestPrice1 <- scatterplot3d(senAn_162_teValuePestPrice1$SSTValue, senAn_162_teValuePestPrice1$pestPrice, senAn_162_teValuePestPrice1$landAv,
    main = "\nRoot crop farm",
    col.main = "#CC3300",
    angle = 65,
    xlab = "SST acquisition costs (%)",
    ylab = "Pesticide costs (%)",
    zlab = "Farm size (ha)",
    scale.y = 0.6,
    axis = TRUE,
    tick.marks = TRUE,
    label.tick.marks = TRUE,
    xlim = c(50,150),
    ylim = c(100,400),
    zlim = c(50,400),
    lab = c(4,6),
    lab.z = c(5),
    font.lab = 2,
    cex.symbols = 1.12,
    cex.axis = 0.9,
    cex.lab = 1.1,
    y.axis.offset = 0.3,
    mar = c(2,3,2,1),
    col.axis = "#CC3300",
    col.lab = "#000000",
    pch = shapes1teValuePestPrice_162,
    #type ="h",
    color = colors1teValuePestPrice_162,
    #grid = FALSE,
    box = FALSE)
PsenAn_151_teValuePestPrice1 <- scatterplot3d(senAn_151_teValuePestPrice1$SSTValue, senAn_151_teValuePestPrice1$pestPrice, senAn_151_teValuePestPrice1$landAv,
    angle = 65,
    main = "\nCereal farm",
    col.main = "#CC9900",
    xlab = "",
    ylab = "",
    zlab = "",
    scale.y = 0.6,
    axis = TRUE,
    tick.marks = TRUE,
    label.tick.marks = TRUE,
    xlim = c(50,150),
    ylim = c(100,400),
    zlim = c(50,400),
    lab = c(4,6),
    lab.z = c(5),
    cex.symbols = 1.12,
    cex.axis = 0.9,
    y.axis.offset = 0.3,
    mar = c(2,4,2,0),
    col.axis = "#CC9900",
    col.lab = "#000000",
    pch = shapes1teValuePestPrice_151,
    #type ="h",
    color = colors1teValuePestPrice_151,
    #grid = FALSE,
    box = FALSE)
PsenAn_162_teValuePestPrice2 <- scatterplot3d(senAn_162_teValuePestPrice2$SSTValue, senAn_162_teValuePestPrice2$pestPrice, senAn_162_teValuePestPrice2$landAv,
    angle = 65,
    xlab = "SST acquisition costs (%)",
    ylab = "Pesticide costs (in %)",
    zlab = "Farm size (ha)",
    scale.y = 0.6,
    axis = TRUE,
    tick.marks = TRUE,
    label.tick.marks = TRUE,
    xlim = c(50,150),
    ylim = c(100,400),
    zlim = c(50,400),
    lab = c(4,6),
    lab.z = c(5),
    font.lab = 2,
    cex.symbols = 1.12,
    cex.axis = 0.9,
    cex.lab = 1.1,
    y.axis.offset = 0.3,
    mar = c(3,3,1,1),
    col.axis = "#CC3300",
    col.lab = "#000000",
    pch = shapes2teValuePestPrice_162,
    #type ="h",
    color = colors2teValuePestPrice_162,
    #grid = FALSE,
    box = FALSE)
PsenAn_151_teValuePestPrice2 <- scatterplot3d(senAn_151_teValuePestPrice2$SSTValue, senAn_151_teValuePestPrice2$pestPrice, senAn_151_teValuePestPrice2$landAv,
    angle = 65,
    xlab = "",
    ylab = "",
    zlab = "",
    scale.y = 0.6,
    axis = TRUE,
    tick.marks = TRUE,
    label.tick.marks = TRUE,
    xlim = c(50,150),
    ylim = c(100,400),
    zlim = c(50,400),
    lab = c(4,6),
    lab.z = c(5),
    cex.symbols = 1.12,
    cex.axis = 0.9,
    y.axis.offset = 0.3,
    mar = c(3,4,1,0),
    col.axis = "#CC9900",
    col.lab = "#000000",
    pch = shapes2teValuePestPrice_151,
    #type ="h",
    color = colors2teValuePestPrice_151,
    #grid = FALSE,
    box = FALSE)






dev.off()
layout(matrix(c(1,2,3,4,5,6), nrow = 2, ncol = 3, byrow = TRUE))
PsenAn_162_teValueAnnFee1 <- scatterplot3d(senAn_162_teValueAnnFee1$SSTValue, senAn_162_teValueAnnFee1$annFee, senAn_162_teValueAnnFee1$landAv,
    angle = 78,
    main = "\nRoot crop farm",
    col.main = "#CC3300", 
    xlab = "",
    ylab = "",
    zlab = "",
    scale.y = 1,
    axis = TRUE,
    tick.marks = TRUE,
    label.tick.marks = TRUE,
    xlim = c(50,150),
    ylim = c(0,15000),
    zlim = c(50,400),
    lab = c(4,6),
    lab.z = c(5),
    cex.symbols = 1.3,
    cex.axis = 0.9,
    y.axis.offset = 0.3,
    mar = c(2,3,0,0),
    col.axis = "#CC3300",
    col.lab = "#000000",
    pch = shapes1teValueAnnFee_162,
    #type ="h",
    color = colors1teValueAnnFee_162,
    #grid = FALSE,
    box = FALSE)
PsenAn_162_teValueAnnFee2 <- scatterplot3d(senAn_162_teValueAnnFee2$SSTValue, senAn_162_teValueAnnFee2$annFee, senAn_162_teValueAnnFee2$landAv,
    angle = 78,
    main = "\nRoot crop farm",
    col.main = "#CC3300", 
    xlab = "SST acquisition costs (%)",
    ylab = "Annual fee (€)",
    zlab = "Farm size (ha)",
    scale.y = 1,
    axis = TRUE,
    tick.marks = TRUE,
    label.tick.marks = TRUE,
    xlim = c(50,150),
    ylim = c(0,15000),
    zlim = c(50,400),
    lab = c(4,6),
    lab.z = c(5),
    font.lab = 2,
    cex.lab = 1.3,
    cex.symbols = 1.3,
    cex.axis = 0.9,
    y.axis.offset = 0.3,
    mar = c(2,3,0,0),
    col.axis = "#CC3300",
    col.lab = "#000000",
    pch = shapes2teValueAnnFee_162,
    #type ="h",
    color = colors2teValueAnnFee_162,
    #grid = FALSE,
    box = FALSE)
PsenAn_151_teValueAnnFee2 <- scatterplot3d(senAn_151_teValueAnnFee2$SSTValue, senAn_151_teValueAnnFee2$annFee, senAn_151_teValueAnnFee2$landAv,
    angle = 78,
    main = "\nCereal farm",
    col.main = "#CC9900",
    xlab = "",
    ylab = "",
    zlab = "",
    scale.y = 1,
    axis = TRUE,
    tick.marks = TRUE,
    label.tick.marks = TRUE,
    xlim = c(50,150),
    ylim = c(0,15000),
    zlim = c(50,400),
    lab = c(4,6),
    lab.z = c(5),
    cex.symbols = 1.3,
    cex.axis = 0.9,
    y.axis.offset = 0.3,
    mar = c(2,3,0,0),
    col.axis = "#CC9900",
    col.lab = "#000000",
    pch = shapes2teValueAnnFee_151,
    #type ="h",
    color = colors2teValueAnnFee_151,
    #grid = FALSE,
    box = FALSE)
PsenAn_162_teValueAlgoCosts1 <- scatterplot3d(senAn_162_teValueAlgoCosts1$SSTValue, senAn_162_teValueAlgoCosts1$algCosts, senAn_162_teValueAlgoCosts1$landAv,
    angle = 78,
    xlab = "",
    ylab = "",
    zlab = "",
    scale.y = 1.25,
    axis = TRUE,
    tick.marks = TRUE,
    label.tick.marks = TRUE,
    xlim = c(50,150),
    ylim = c(0,12),
    zlim = c(50,400),
    lab = c(4,6),
    lab.z = c(5),
    cex.symbols = 1.3,
    cex.axis = 0.9,
    y.axis.offset = 0.3,
    mar = c(3,3,0,0),
    col.axis = "#CC3300",
    col.lab = "#000000",
    pch = shapes1teValueAlgoCosts_162,
    #type ="h",
    color = colors1teValueAlgoCosts_162,
    #grid = FALSE,
    box = FALSE)
PsenAn_162_teValueAlgoCosts2 <- scatterplot3d(senAn_162_teValueAlgoCosts2$SSTValue, senAn_162_teValueAlgoCosts2$algCosts, senAn_162_teValueAlgoCosts2$landAv,
    angle = 78,
    xlab = "SST acquisition costs (%)",
    ylab = "Ha fee (€)",
    zlab = "Farm size (ha)",
    scale.y = 1.25,
    axis = TRUE,
    tick.marks = TRUE,
    label.tick.marks = TRUE,
    xlim = c(50,150),
    ylim = c(0,12),
    zlim = c(50,400),
    lab = c(4,6),
    lab.z = c(5),
    font.lab = 2,
    cex.lab = 1.3,
    cex.symbols = 1.3,
    cex.axis = 0.9,
    y.axis.offset = 0.3,
    mar = c(3,3,0,0),
    col.axis = "#CC3300",
    col.lab = "#000000",
    pch = shapes2teValueAlgoCosts_162,
    #type ="h",
    color = colors2teValueAlgoCosts_162,
    #grid = FALSE,
    box = FALSE)
PsenAn_151_teValueAlgoCosts2 <- scatterplot3d(senAn_151_teValueAlgoCosts2$SSTValue, senAn_151_teValueAlgoCosts2$algCosts, senAn_151_teValueAlgoCosts2$landAv,
    angle = 78,
    xlab = "",
    ylab = "",
    zlab = "",
    scale.y = 1.25,
    axis = TRUE,
    tick.marks = TRUE,
    label.tick.marks = TRUE,
    xlim = c(50,150),
    ylim = c(0,12),
    zlim = c(50,400),
    lab = c(4,6),
    lab.z = c(5),
    cex.symbols = 1.3,
    cex.axis = 0.9,
    y.axis.offset = 0.3,
    mar = c(3,3,0,0),
    col.axis = "#CC9900",
    col.lab = "#000000",
    pch = shapes2teValueAlgoCosts_151,
    #type ="h",
    color = colors2teValueAlgoCosts_151,
    #grid = FALSE,
    box = FALSE)




layout(matrix(c(1,2,3,4), nrow = 2, ncol = 2, byrow = TRUE))
PsenAn_151_teValueAnnFee1 <- scatterplot3d(senAn_151_teValueAnnFee1$SSTValue, senAn_151_teValueAnnFee1$annFee, senAn_151_teValueAnnFee1$landAv,
    main = "\nCereal farm",
    col.main = "#CC9900",
    angle = 70,
    xlab = "SST acquisition costs (%)",
    ylab = "Annual fee (€)",
    zlab = "Farm size (ha)",
    scale.y = 0.6,
    axis = TRUE,
    tick.marks = TRUE,
    label.tick.marks = TRUE,
    xlim = c(50,150),
    ylim = c(0,15000),
    zlim = c(50,400),
    lab = c(4,6),
    lab.z = c(5),
    font.lab = 2,
    cex.symbols = 1.12,
    cex.axis = 0.9,
    cex.lab = 1.1,
    y.axis.offset = 0.4,
    mar = c(0,3,2,3),
    col.axis = "#CC9900",
    col.lab = "#000000",
    pch = shapes1teValueAnnFee_151,
    #type ="h",
    color = colors1teValueAnnFee_151,
    #grid = FALSE,
    box = FALSE)
PsenAn_151_teValueAlgoCosts1 <- scatterplot3d(senAn_151_teValueAlgoCosts1$SSTValue, senAn_151_teValueAlgoCosts1$algCosts, senAn_151_teValueAlgoCosts1$landAv,
    angle = 78,
    main = "\nCereal farm",
    col.main = "#CC9900",
    xlab = "SST acquisition costs (%)",
    ylab = "Ha fee (€)",
    zlab = "Farm size (ha)",
    scale.y = 1.25,
    axis = TRUE,
    tick.marks = TRUE,
    label.tick.marks = TRUE,
    xlim = c(50,150),
    ylim = c(0,12),
    zlim = c(50,400),
    lab = c(4,6),
    lab.z = c(5),
    font.lab = 2,
    cex.symbols = 1.12,
    cex.axis = 0.9,
    cex.lab = 1.1,
    y.axis.offset = 0.3,
    mar = c(0,3,2,3),
    col.axis = "#CC9900",
    col.lab = "#000000",
    pch = shapes1teValueAlgoCosts_151,
    #type ="h",
    color = colors1teValueAlgoCosts_151,
    #grid = FALSE,
    box = FALSE)
    ?scatterplot3d
